# quay.io/tiran/ipa-hcc-ci:9
FROM quay.io/centos/centos:stream9
COPY ipa-hcc.spec /tmp/
RUN dnf update -y \
    && dnf install --nodocs --setopt=install_weak_deps=False -y --best \
        rpm-build createrepo dnf-utils \
    && dnf builddep --nodocs --setopt=install_weak_deps=False -y --best \
        --spec /tmp/ipa-hcc.spec \
    && dnf clean all
VOLUME /ipa-hcc
WORKDIR /ipa-hcc
