# see quay.io/podengo/ipa-hcc-ci:8
FROM quay.io/centos/centos:stream8
COPY ipa-hcc.spec /tmp/
RUN dnf update -y \
    && dnf -y module enable idm:DL1 \
    && dnf install --nodocs --setopt=install_weak_deps=False -y --best \
        rpm-build createrepo dnf-utils \
    && dnf builddep --nodocs --setopt=install_weak_deps=False -y --best \
        --spec /tmp/ipa-hcc.spec \
    && dnf clean all
VOLUME /ipa-hcc
WORKDIR /ipa-hcc
